#!/bin/bash
# HAT OS - دليل التثبيت اليدوي على Steam Deck LCD
# للاستخدام عندما يكون Arch Linux مثبتاً مسبقاً (مثلاً بدل Windows)

set -euo pipefail

echo "╔══════════════════════════════════════════╗"
echo "║      HATAN OS - تثبيت على Steam Deck     ║"
echo "╚══════════════════════════════════════════╝"
echo ""
echo "⚠️  تحذير: هذا سيستبدل Windows بنظام HATAN OS"
echo ""
read -rp "هل تريد المتابعة؟ (yes/no): " confirm
[[ "$confirm" == "yes" ]] || { echo "أُلغي."; exit 0; }

echo ""
echo "الخطوة 1: تحضير USB"
echo "─────────────────────"
echo "  1. حمّل Arch Linux ISO من: https://archlinux.org/download/"
echo "  2. اكتبها على USB باستخدام Rufus أو balenaEtcher"
echo "  3. أدخل Steam Deck في وضع Boot من USB:"
echo "     - أطفئ الجهاز"
echo "     - اضغط Volume+ و Power معاً"
echo "     - اختر Boot Manager → USB"
echo ""
read -rp "اضغط Enter عندما تكون جاهزاً..."

echo ""
echo "الخطوة 2: تثبيت Arch Linux"
echo "───────────────────────────"
echo "  على Steam Deck من USB، نفّذ:"
echo ""
echo "  # تقسيم القرص"
echo "  lsblk"
echo "  cfdisk /dev/nvme0n1"
echo "    - EFI: 512M (type: EFI System)"
echo "    - Root: باقي المساحة (type: Linux filesystem)"
echo ""
echo "  # تهيئة"
echo "  mkfs.fat -F32 /dev/nvme0n1p1"
echo "  mkfs.ext4 /dev/nvme0n1p2"
echo ""
echo "  # تثبيت Arch"
echo "  mount /dev/nvme0n1p2 /mnt"
echo "  mount /dev/nvme0n1p1 /mnt/boot"
echo "  pacstrap /mnt base base-devel linux-firmware"
echo "  genfstab -U /mnt >> /mnt/etc/fstab"
echo "  arch-chroot /mnt"
echo ""
read -rp "اضغط Enter عند اكتمال تثبيت Arch..."

echo ""
echo "الخطوة 3: تثبيت HATAN OS"
echo "───────────────────────"
echo "  داخل arch-chroot:"
echo ""
echo "  # انسخ ملفات HATAN OS إلى /opt/hatan-os"
echo "  # (من USB أو عبر git clone)"
echo ""
echo "  cd /opt/hatan-os/installer"
echo "  sudo ./hat-install.sh"
echo ""
echo "  (أو: sudo ./install.sh للطرفية)"
echo ""
echo "  reboot"
echo ""
echo "✅ بعد إعادة التشغيل ستظهر شاشة HATAN OS"
